spring.application.name=iam-service

# Server
server.port=8189

# URL prefix; "/" - without prefix
server.servlet.context-path=/

# Disable banner
spring.main.banner-mode=off

# Spring uses virtual thread
spring.threads.virtual.enabled=true

# OSIV off
spring.jpa.open-in-view=false