spring.application.name=iam-service

# Server
server.port=8189

# URL prefix; "/" - without prefix
server.servlet.context-path=/

# Disable banner
spring.main.banner-mode=off

# Spring uses virtual thread
spring.threads.virtual.enabled=true

# OSIV off
spring.jpa.open-in-view=false

# Spring security
spring.security.user.name=${SPRING_SECURITY_USER_NAME:user}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD:testpassword}
spring.security.user.roles=${SPRING_SECURITY_USER_PASSWORD:USER}

# Jwt
jwt.secret=${JWT_SECRET}
jwt.lifetime=3600
jwt.expiration=604800

# PostgreSQL
POST_HUB_SERVICE_DATABASE=post_hub_local
DEFAULT_SCHEMA=v1_iam_service
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POST_HUB_SERVICE_DATABASE}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Jpa
spring.jpa.properties.hibernate.default_schema=${DEFAULT_SCHEMA}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.jdbc.order_inserts=true
spring.jpa.properties.hibernate.jdbc.order_updates=true
spring.jpa.properties.hibernate.cache.use_second_level_cache=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=${DEFAULT_SCHEMA}
spring.flyway.clean-disabled=false
app.flyway.clean-on-start=false

# End Points
end.point.posts=/posts
end.point.id=/{id}
end.point.create=/create
end.point.all=/all
end.point.search=/search
end.point.users=/users
end.point.auth=/auth
end.point.login=/login
end.point.refresh.token=/refresh/token

# JSON Jackson
spring.jackson.mapper.sort-properties-alphabetically=false

# Logging
logging.level.com.posthub.iam=TRACE
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.com.post_hub.iam_service=DEBUG

spring.output.ansi.enabled=DETECT